version: "3.9"

services:
  gradle:
    image: gradle:8.1.1-jdk11-alpine
    working_dir: /app
    volumes:
      - ./:/app
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: TRUE
      TYPE: SPIGOT
      VERSION: 1.19.3
      MEMORY: 8G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./.minecraft-data:/data
      - ./build/libs/capyland-0.0.1.jar:/data/plugins/capyland.jar
