repl:
  хуй: пісюньчик

rp-nicknames:
  Ziozyun: '[§6Розпіздяй§f] §eЗьозюн'
  Kyryl_Kruhliak: §eКирил Кругляк
  Han__Salo: §eХан Салович
  Snl4ik: '[ПУПСІК] §eВладислав Бандера'
  Pavlic_Sherlock: §eПавлік Шерлок
  capybobr: '§eКапібара'

api-chat:
  zyuninc:
    url: https://zyuninc.zyun.software/api/minecraft
    token: owiejfoiw

mysql:
  url: jdbc:mysql://localhost:3306/db
  user: root
  password: secret

world:
  lobby: world_auth
  main: world

api:
  url: https://example.com/
  token: secret

title:
  register:
    text: §6Потрібна реєстрація
    sub: §aВведіть §6/register §r§6<пароль> <повтор пароля>
  login:
    text: §6Потрібна авторизація
    sub: §aВведіть §6/login §6<пароль>
  portal:
    unapproved: §cВашого персонажа не підтверджено
  lobby: §cВи вже в лобі

message:
  command:
    plugins: Список плагінів недоступний
    help: Текст довідки
    register:
      console: Зареєструватися може лише гравець!
      args: §c/register <пароль> <повторення паролю>
      different-passwords: §cПаролі не співпадають. Будь ласка, введіть однакові паролі.
      already-registered: §cВи вже зареєстровані.
    login:
      console: Авторизуватися може лише гравець!
      args: §c/login <пароль>
      registration-is-required: §cНеобхідно зареєструватися.
      already-authorized: §cВи вже авторизовані.
      invalid-password: §cПароль не вірний.
      success: |
        §aВи успішно авторизувалися
        §6Пройдіть в портал для телепортації в основний світ
    logout:
      console: Вийти може лише гравець!
      unauthorized: §cВи не авторизовані.
    lobby:
      console: Повернутися до лобі може лише гравець!
    change-password:
      args: §c/змінити_пароль <новий пароль> <повторення нового паролю> <старий пароль>
      changed: §aПароль змінено.
    discord:
      console: 'Прив''язати обліковий запис Discord може тільки гравець!'
      args: §c/діскорд <код> <пароль>
      success: '§aDiscord прив''язано'
      error: '§cПомилка прив''язки Discord'
    hidden-command:
      approve-player:
        not-found: §cГравця для підтвердження не знайдено.
        approved: §aГравця підтверджено.
        canceled: §aПідтвердження гравця скасовано.
        not-changed: §cПідтвердження гравця не було змінено.
