name: CapyLand
version: 1.0
api-version: 1.20
author: ZyunSoftware - CapyDevMC
main: com.zyunsoftware.capydevmc.app.CapylandPlugin
description: Основний плагін Долини Капібар

commands:
  api:
    description: Робота з API
    usage: /api

  перезавантажити_конфігураційний_файл:
    description: Перезавантаження конфігураційного файлу
    usage: /перезавантажити_конфігураційний_файл

