name: CapyLand
version: 1.0
api-version: 1.20
author: ZyunSoftware - CapyDevMC
main: com.zyunsoftware.capydevmc.app.CapylandPlugin
description: Основний плагін Долини Капібар

depends:
  - Multiverse-Core
  - TAB

commands:
  register:
    description: Реєстрація
    usage: /register <пароль> <повторення паролю>

  login:
    description: Авторизація
    usage: /login <пароль>

  вихід:
    description: Вийти
    usage: /вихід

  до_лобі:
    description: Повернутися до лобі
    usage: /до_лобі

  змінити_пароль:
    description: Зміна паролю
    usage: /змінити_пароль <новий пароль> <повторення нового паролю> <старий пароль>

  діскорд:
    description: Прив'язка облікового запису Discord
    usage: /діскорд <код> <пароль>
