name: CapyLand
version: 1.0
api-version: 1.20
author: ZyunSoftware - CapyDevMC
main: com.zyunsoftware.capydevmc.app.CapylandPlugin
description: Основний плагін Долини Капібар

depends:
  - Multiverse-Core
  - TAB

commands:
  register:
    description: Реєстрація
    usage: /register <пароль> <повторення паролю>

  login:
    description: Авторизація
    usage: /login <пароль>

  logout:
    description: Вийти
    usage: /logout

  lobby:
    description: Повернутися до лобі
    usage: /lobby
